CREATE TABLE POC_UNIT_HIER (
    UNIT_SKEY INT NOT NULL,
    DOMAIN_ID INT NOT NULL,
    LOCALE_CODE VARCHAR(10) NOT NULL,
    UNIT_ORG_ATTR_SKEY SMALLINT,
    UNIT_ORG_LEVEL SMALLINT
    UNIT_ID VARCHAR(50) NOT NULL,
    UNIT_NAME VARCHAR(100) NOT NULL,
    UNIT_LEVEL_DESC VARCHAR(100),
    UNIT_STATUS_CODE VARCHAR(10),
    UNIT_STATUS VARCHAR(50),
    CORP_ID VARCHAR(50) NOT NULL,
    CORP_SKEY INT NOT NULL,
    CORP_NAME VARCHAR(100) NOT NULL,
    CORP_LEVEL_DESC VARCHAR(100),
    
    LEVEL_ID_1 VARCHAR(50),
    LEVEL_SKEY_1 INT,
    LEVEL_NAME_1 VARCHAR(100),
    LEVEL_DESC_1 VARCHAR(100),
    
    LEVEL_ID_2 VARCHAR(50),
    LEVEL_SKEY_2 INT,
    LEVEL_NAME_2 VARCHAR(100),
    LEVEL_DESC_2 VARCHAR(100),
    
    LEVEL_ID_3 VARCHAR(50),
    LEVEL_SKEY_3 INT,
    LEVEL_NAME_3 VARCHAR(100),
    LEVEL_DESC_3 VARCHAR(100),
    
    LEVEL_ID_4 VARCHAR(50),
    LEVEL_SKEY_4 INT,
    LEVEL_NAME_4 VARCHAR(100),
    LEVEL_DESC_4 VARCHAR(100),
    
    LEVEL_ID_5 VARCHAR(50),
    LEVEL_SKEY_5 INT,
    LEVEL_NAME_5 VARCHAR(100),
    LEVEL_DESC_5 VARCHAR(100),
    
    DISTRICT_ID VARCHAR(50),
    DISTRICT_SKEY INT ,
    DISTRICT_NAME VARCHAR(100) ,
    DISTRICT_DESC VARCHAR(100),
    
    STORE_ID VARCHAR(50),
    STORE_SKEY INT,
    STORE_NAME VARCHAR(100) ,
    STORE_DESC VARCHAR(100),
    STORE_LEVEL_FLAG SMALLINT,
    CREATE_DATE_TIME TIMESTAMP,
    UPDATE_DATE_TIME TIMESTAMP,
    PRIMARY KEY (UNIT_SKEY,DOMAIN_ID,LOCALE_CODE,UNIT_ORG_LEVEL)
);


CREATE TABLE POC_PROJECT (
    PROJECT_SKEY INT NOT NULL,
    COMPLETION_DATE_SKEY INT NOT NULL,
    DOMAIN_ID INT NOT NULL,
    FINISH_DATE_SKEY INT NOT NULL,
    START_DATE_SKEY INT NOT NULL,
    LAUNCH_DATE_SKEY INT NOT NULL,
    CREATE_DATE_SKEY INT NOT NULL,

    CREATOR_DEPT_SKEY INT NOT NULL,
    RES_DEPT_SKEY INT NOT NULL,
    RES_ROLE_SKEY INT NOT NULL,
    PROJECT_TYPE_SKEY INT NOT NULL,
    CREATOR_UNIT_SKEY INT NOT NULL,
    CREATOR_SKEY INT NOT NULL,
    APPROVER_SKEY INT NOT NULL,
    STATUS_SKEY INT NOT NULL,
    PARENT_PROJECT_SKEY INT,
    PROJECT_ID VARCHAR(50) NOT NULL,
    
    START_DATE_TIMESTAMP TIMESTAMP,
    FINISH_DATE_TIMESTAMP TIMESTAMP,
    LAUNCH_DATE_TIMESTAMP TIMESTAMP,
    CREATE_DATE_TIMESTAMP TIMESTAMP,
    COMPLETION_DATE_TIMESTAMP TIMESTAMP,

    NUM_PROJECTS INT,
    NUM_D_PROJECTS INT,
    NUM_P_PROJECTS INT,
    NUM_R_PROJECTS INT,
    NUM_C_PROJECTS INT,
    NUM_F_PROJECTS INT,
    NUM_O_PROJECTS INT,
    STORE_COUNT INT,
    AUTO_COMPL_FLAG SMALLINT,
    PROJECT_CATEGORY VARCHAR(100),
    PROJECT_SUB_CATEGORY VARCHAR(100),
    PRIMARY KEY (PROJECT_SKEY,DOMAIN_ID,COMPLETION_DATE_SKEY)
    );

    
CREATE TABLE POC_PROJECT_EXECUTION (
    EXECUTION_SKEY INT NOT NULL,
    COMPLETION_DATE_SKEY INT NOT NULL,
    DOMAIN_ID INT NOT NULL,
    FINISH_DATE_SKEY INT NOT NULL,
    START_DATE_SKEY INT NOT NULL,
    LAUNCH_DATE_SKEY INT NOT NULL,
    CREATE_DATE_SKEY INT NOT NULL,

    UNIT_SKEY INT NOT NULL,
    PROJECT_SKEY   INT NOT NULL,
    UNIT_ID VARCHAR(50) NOT NULL,
    PROJECT_ID VARCHAR(50) NOT NULL,

    EXEC_COMPLETION_DATE_SKEY INT NOT NULL,
    EXEC_START_DATE_SKEY INT NOT NULL,
    EXEC_FINISH_DATE_SKEY INT NOT NULL,
    

    CREATOR_DEPT_SKEY INT NOT NULL,
    RES_DEPT_SKEY INT NOT NULL,
    RES_ROLE_SKEY INT NOT NULL,
    ASSIGNED_USER_SKEY INT NOT NULL,
    PROJECT_TYPE_SKEY INT NOT NULL,
    STATUS_SKEY INT NOT NULL,
    CREATOR_UNIT_SKEY INT NOT NULL,
    
    NUM_TOT_PROJECTS INT,
    NUM_N_PROJECTS INT,
    NUM_P_PROJECTS INT,
    NUM_R_PROJECTS INT,
    NUM_C_PROJECTS INT,
    NUM_F_PROJECTS INT,
    NUM_O_PROJECTS INT,
    NUM_CO_PROJECTS INT,
    AUTO_COMPL_FLAG SMALLINT,
    
    EXEC_START_DATE_TIMESTAMP TIMESTAMP,
    EXEC_FINISH_DATE_TIMESTAMP TIMESTAMP,
    EXEC_COMPLETION_DATE_TIMESTAMP TIMESTAMP,

    PRIMARY KEY (PROJECT_ID,DOMAIN_ID,UNIT_ID,COMPLETION_DATE_SKEY)
    );


CREATE TABLE POC_STATUS_D(
    LOCALE_CODE VARCHAR(10) NOT NULL,
    STATUS_SKEY INT NOT NULL,
    DOMAIN_ID INT NOT NULL,
    STATUS_CODE VARCHAR(50) NOT NULL,
    STATUS_DESC VARCHAR(100),
    PRIMARY KEY (STATUS_SKEY,DOMAIN_ID,LOCALE_CODE)
);
